"use client";

import { useState } from "react";

const steps = ["Business", "Property", "Details", "Photos", "Rates & fees", "Policies", "Payments", "Calendars", "Review"];
const amenities = ["Wi-Fi", "Hot tub", "Pool", "Pet friendly", "Fire pit", "Waterfront", "Full kitchen", "Washer / dryer", "Self check-in", "Wheelchair friendly", "Boat parking", "EV charging", "Fireplace", "Grill", "Game room", "Outdoor seating"];
const commonPolicies = ["No smoking indoors", "No parties or unauthorized events", "Registered guests only", "Pets must be included on the reservation", "Children must be supervised", "Quiet hours apply", "No commercial photography", "No fireworks", "No glass near pool / hot tub", "Exterior security cameras disclosed", "Guests responsible for excessive damage", "Parking limited to designated areas"];

export function HostOnboardingWizard() {
  const [step, setStep] = useState(0);
  const next = () => setStep((value) => Math.min(value + 1, steps.length - 1));
  const previous = () => setStep((value) => Math.max(value - 1, 0));

  return (
    <div className="wizard near-production-wizard">
      <aside className="wizard-steps">{steps.map((label, index) => <button type="button" className={step === index ? "active" : step > index ? "done" : ""} onClick={() => setStep(index)} key={label}><span>{step > index ? "✓" : index + 1}</span><b>{label}</b></button>)}</aside>
      <section className="panel wizard-panel">
        <div className="wizard-progress"><span>Step {step + 1} of {steps.length}</span><i><b style={{width: `${((step + 1) / steps.length) * 100}%`}}/></i></div>

        {step === 0 && <><p className="eyebrow dark">Business</p><h2>Start with the person or business behind the stay.</h2><p>This is the host organization that manages listings and receives platform notices.</p><div className="field-grid onboarding-fields"><label className="full"><span>Business or host name</span><input placeholder="Business or host name"/></label><label><span>Primary contact</span><input placeholder="Full name"/></label><label><span>Phone</span><input type="tel" placeholder="Phone number"/></label><label className="full"><span>Business email</span><input type="email" placeholder="Email address"/></label><label className="full"><span>Business location</span><input placeholder="City, state"/></label></div></>}

        {step === 1 && <><p className="eyebrow dark">Property</p><h2>Tell travelers what they are booking.</h2><div className="field-grid onboarding-fields"><label className="full"><span>Property name</span><input placeholder="Public listing name"/></label><label><span>Property type</span><select defaultValue=""><option value="" disabled>Select type</option><option>Cabin</option><option>House</option><option>Cottage</option><option>Lodge</option><option>Condo</option><option>RV Site</option><option>Glamping</option><option>Tiny Home</option><option>Other</option></select></label><label><span>Location</span><input placeholder="City, state"/></label><label className="full"><span>Short description</span><textarea placeholder="What makes this stay worth the trip?"/></label></div></>}

        {step === 2 && <><p className="eyebrow dark">Details</p><h2>Choose the basics guests search and filter by.</h2><div className="field-grid onboarding-fields"><label><span>Maximum guests</span><input type="number" min="1" placeholder="0"/></label><label><span>Bedrooms</span><input type="number" min="0" placeholder="0"/></label><label><span>Bathrooms</span><input type="number" min="0" step="0.5" placeholder="0"/></label><label><span>Default minimum stay</span><input type="number" min="1" placeholder="Nights"/></label></div><p className="picker-label">Amenities</p><div className="amenity-picker">{amenities.map((item)=><label key={item}><input type="checkbox"/><span>{item}</span></label>)}</div><label className="full custom-option"><span>Other amenities</span><textarea placeholder="Add anything important that is not listed above."/></label></>}

        {step === 3 && <><p className="eyebrow dark">Photos</p><h2>Lead with the photos that make the stay worth the drive.</h2><div className="upload-drop"><span>＋</span><strong>Add property photos</strong><p>Drag photos here or choose files. The first image will become the listing cover.</p><button type="button" className="button button-small button-quiet">Choose photos</button></div><div className="photo-slots">{[1,2,3,4].map((item)=><div key={item}><span>{item === 1 ? "Cover" : `Photo ${item}`}</span></div>)}</div></>}

        {step === 4 && <><p className="eyebrow dark">Rates & fees</p><h2>Keep lodging and host fees clearly separated.</h2><div className="field-grid onboarding-fields"><label><span>Weeknight rate</span><div className="money-input"><b>$</b><input type="number" min="0" placeholder="0"/></div></label><label><span>Weekend rate</span><div className="money-input"><b>$</b><input type="number" min="0" placeholder="0"/></div></label><label><span>Cleaning fee</span><div className="money-input"><b>$</b><input type="number" min="0" placeholder="0"/></div></label><label><span>Pet fee</span><div className="money-input"><b>$</b><input type="number" min="0" placeholder="0"/></div></label></div><div className="inline-note"><strong>Find A Place commission is based on lodging only.</strong><span>The 5% partner or 7% standard commission is calculated from the nightly lodging subtotal after host discounts, not legitimate cleaning fees, pet fees, taxes, refundable deposits or optional add-ons.</span></div></>}

        {step === 5 && <><p className="eyebrow dark">Policies</p><h2>Choose the rules that apply to this property.</h2><p>Select common policies instead of rewriting them from scratch. Only checked policies will be shown to guests.</p><div className="field-grid onboarding-fields"><label><span>Check-in</span><input type="time"/></label><label><span>Checkout</span><input type="time"/></label><label className="full"><span>Cancellation policy</span><select defaultValue=""><option value="" disabled>Select a cancellation policy</option><option value="flexible">Flexible</option><option value="moderate">Moderate</option><option value="firm">Firm</option><option value="strict">Strict</option></select></label></div><p className="picker-label">Common house rules</p><div className="amenity-picker policy-picker">{commonPolicies.map((item)=><label key={item}><input type="checkbox"/><span>{item}</span></label>)}</div><label className="full custom-option"><span>Custom policies</span><textarea placeholder="Add uncommon or property-specific rules that are not covered above."/></label></>}

        {step === 6 && <><p className="eyebrow dark">Payments</p><h2>Connect the account that will receive booking money.</h2><p>Payout and identity details will stay with the secure payment provider rather than being stored in the Find A Place Booking database.</p><div className="connection-card"><div className="connection-icon">$</div><div><strong>Payout setup comes after the host record is saved</strong><span>The production payment connection will use secure provider onboarding. No bank or identity information is collected in this shell.</span></div><button type="button" className="button button-small" disabled>Connect payments</button></div></>}

        {step === 7 && <><p className="eyebrow dark">Calendars</p><h2>Keep availability aligned with the channels you already use.</h2><p>The property’s source-of-truth calendar will be connected after the property record exists so outside bookings do not appear open here.</p><div className="connection-card"><div className="connection-icon">↻</div><div><strong>No calendar connected yet</strong><span>iCal will provide broad compatibility, with direct PMS integrations added according to host demand.</span></div><button type="button" className="button button-small" disabled>Add calendar</button></div></>}

        {step === 8 && <><p className="eyebrow dark">Review</p><h2>Review will summarize the real property record.</h2><div className="review-card"><div><span>Listing</span><strong>Complete property details required</strong></div><div><span>Amenities</span><strong>Selected amenities will appear here</strong></div><div><span>Policies</span><strong>Selected and custom policies will appear here</strong></div><div><span>Payments</span><strong>Not connected</strong></div><div><span>Calendar</span><strong>Not connected</strong></div></div><label className="checkline"><input type="checkbox"/><span>I confirm that I have authority to list this property and that the listing information is accurate.</span></label><div className="submit-ready submit-pending"><span>○</span><div><strong>Submission is not active yet</strong><p>The real property save/review workflow will be enabled when host accounts and properties are connected to Supabase.</p></div></div></>}

        <div className="wizard-actions"><button type="button" className="button button-quiet" disabled={step === 0} onClick={previous}>← Back</button>{step < steps.length - 1 ? <button type="button" className="button" onClick={next}>Continue to {steps[step + 1]} →</button> : <button type="button" className="button" disabled>Submit property for review</button>}</div>
      </section>
      <aside className="onboarding-plan"><small>Platform commission</small><strong>5%</strong><span>Find A Place partner properties</span><hr/><p>Other hosts are 7%. Commission applies to the nightly lodging subtotal after host discounts, not legitimate host fees, taxes, refundable deposits or optional add-ons.</p><div className="plan-points"><span>✓ Branded booking page</span><span>✓ Marketplace visibility</span><span>✓ Host dashboard</span><span>✓ Calendar connections</span></div></aside>
    </div>
  );
}
