"use client";

import Link from "next/link";
import { useState } from "react";

const steps = ["Business", "Property", "Details", "Photos", "Rates & fees", "Policies", "Payments", "Calendars", "Review"];

export function HostOnboardingWizard() {
  const [step, setStep] = useState(0);
  const [paymentConnected, setPaymentConnected] = useState(false);
  const [calendarConnected, setCalendarConnected] = useState(false);

  const next = () => setStep((value) => Math.min(value + 1, steps.length - 1));
  const previous = () => setStep((value) => Math.max(value - 1, 0));

  return (
    <div className="wizard near-production-wizard">
      <aside className="wizard-steps">
        {steps.map((label, index) => <button type="button" className={step === index ? "active" : step > index ? "done" : ""} onClick={() => setStep(index)} key={label}><span>{step > index ? "✓" : index + 1}</span><b>{label}</b></button>)}
      </aside>
      <section className="panel wizard-panel">
        <div className="wizard-progress"><span>Step {step + 1} of {steps.length}</span><i><b style={{width: `${((step + 1) / steps.length) * 100}%`}}/></i></div>
        {step === 0 && <><p className="eyebrow dark">Business</p><h2>Start with the person or business behind the stay.</h2><p>This is the account that manages listings and receives platform notices.</p><div className="field-grid onboarding-fields"><label className="full"><span>Business or host name</span><input defaultValue="Fancy Hill Cabins & RV Park LLC"/></label><label><span>Primary contact</span><input defaultValue="Renea"/></label><label><span>Phone</span><input defaultValue="(870) 555-0144"/></label><label className="full"><span>Business email</span><input defaultValue="host@example.com"/></label><label className="full"><span>Business location</span><input defaultValue="Caddo Gap, Arkansas"/></label></div></>}
        {step === 1 && <><p className="eyebrow dark">Property</p><h2>Tell travelers what they are booking.</h2><div className="field-grid onboarding-fields"><label className="full"><span>Property name</span><input defaultValue="Whitetail Cabin"/></label><label><span>Property type</span><select defaultValue="Cabin"><option>Cabin</option><option>House</option><option>Cottage</option><option>Lodge</option><option>RV Site</option><option>Glamping</option></select></label><label><span>Location</span><input defaultValue="Caddo Gap, Arkansas"/></label><label className="full"><span>Short description</span><textarea defaultValue="A quiet cabin near the Caddo River with room for a family weekend and easy access to outdoor recreation."/></label></div></>}
        {step === 2 && <><p className="eyebrow dark">Details</p><h2>Set the basics guests search and filter by.</h2><div className="field-grid onboarding-fields"><label><span>Maximum guests</span><input type="number" defaultValue="6"/></label><label><span>Bedrooms</span><input type="number" defaultValue="2"/></label><label><span>Bathrooms</span><input type="number" defaultValue="2"/></label><label><span>Minimum stay</span><input defaultValue="2 nights"/></label></div><div className="amenity-picker">{["Hot tub","Pet friendly","Fire pit","Waterfront","Wi-Fi","Full kitchen","Self check-in","Wheelchair friendly","Boat parking","EV charging"].map((item,index)=><label key={item}><input type="checkbox" defaultChecked={[0,1,2,4,5,6].includes(index)}/><span>{item}</span></label>)}</div></>}
        {step === 3 && <><p className="eyebrow dark">Photos</p><h2>Lead with the photos that make the stay worth the drive.</h2><div className="upload-drop"><span>＋</span><strong>Add property photos</strong><p>Drag photos here or choose files. The first image becomes the listing cover.</p><button type="button" className="button button-small button-quiet">Choose photos</button></div><div className="photo-slots">{[1,2,3,4].map((item)=><div key={item}><span>{item === 1 ? "Cover" : `Photo ${item}`}</span></div>)}</div></>}
        {step === 4 && <><p className="eyebrow dark">Rates & fees</p><h2>Set the price the way you already run the property.</h2><div className="field-grid onboarding-fields"><label><span>Weeknight rate</span><div className="money-input"><b>$</b><input defaultValue="169"/></div></label><label><span>Weekend rate</span><div className="money-input"><b>$</b><input defaultValue="199"/></div></label><label><span>Cleaning fee</span><div className="money-input"><b>$</b><input defaultValue="75"/></div></label><label><span>Pet fee</span><div className="money-input"><b>$</b><input defaultValue="35"/></div></label></div><div className="inline-note"><strong>Seasonal pricing comes next.</strong><span>Holiday dates, fall weekends and other rate rules can be added from the host dashboard after launch.</span></div></>}
        {step === 5 && <><p className="eyebrow dark">Policies</p><h2>Your property, your house rules.</h2><div className="field-grid onboarding-fields"><label><span>Check-in</span><input type="time" defaultValue="15:00"/></label><label><span>Checkout</span><input type="time" defaultValue="11:00"/></label><label className="full"><span>Cancellation policy</span><select defaultValue="moderate"><option value="flexible">Flexible — full refund 5 days before</option><option value="moderate">Moderate — full refund 7 days before</option><option value="firm">Firm — partial refund before arrival</option></select></label><label className="full"><span>House rules</span><textarea defaultValue="No smoking indoors. Registered guests only. Quiet hours after 10 PM. Pets must be included on the reservation."/></label></div></>}
        {step === 6 && <><p className="eyebrow dark">Payments</p><h2>Connect the account that receives guest payments.</h2><p>Payout and identity details stay with the secure payment provider rather than being stored in the Find A Place Booking database.</p><div className={`connection-card ${paymentConnected ? "connected" : ""}`}><div className="connection-icon">{paymentConnected ? "✓" : "$"}</div><div><strong>{paymentConnected ? "Payout account connected" : "Connect payout account"}</strong><span>{paymentConnected ? "Business verification complete · Bank ending 4812" : "Verify the business and choose where booking payouts should settle."}</span></div><button type="button" className="button button-small" onClick={() => setPaymentConnected(true)}>{paymentConnected ? "Connected" : "Connect payments"}</button></div></>}
        {step === 7 && <><p className="eyebrow dark">Calendars</p><h2>Keep availability aligned with the channels you already use.</h2><p>Connect the main property calendar so dates booked elsewhere do not appear open in Find A Place Booking.</p><div className={`connection-card ${calendarConnected ? "connected" : ""}`}><div className="connection-icon">{calendarConnected ? "✓" : "↻"}</div><div><strong>{calendarConnected ? "Main calendar connected" : "Connect an availability feed"}</strong><span>{calendarConnected ? "Last sync just now · No conflicts found" : "OwnerRez, Airbnb, Vrbo and other iCal-compatible calendars can be used."}</span></div><button type="button" className="button button-small" onClick={() => setCalendarConnected(true)}>{calendarConnected ? "Connected" : "Add calendar"}</button></div></>}
        {step === 8 && <><p className="eyebrow dark">Review</p><h2>Whitetail Cabin is ready for review.</h2><div className="review-card"><div><span>Listing</span><strong>Whitetail Cabin · Caddo Gap, Arkansas</strong></div><div><span>Occupancy</span><strong>6 guests · 2 bedrooms · 2 baths</strong></div><div><span>Base pricing</span><strong>$169 weekdays · $199 weekends</strong></div><div><span>Payments</span><strong>{paymentConnected ? "Connected" : "Can be completed before launch"}</strong></div><div><span>Calendar</span><strong>{calendarConnected ? "Connected" : "Can be completed before launch"}</strong></div></div><label className="checkline"><input type="checkbox" defaultChecked/><span>I confirm that I have authority to list this property and that the listing information is accurate.</span></label><div className="submit-ready"><span>✓</span><div><strong>Ready to submit</strong><p>Once approved, the property can appear in traveler searches for dates it is available.</p></div></div></>}
        <div className="wizard-actions"><button type="button" className="button button-quiet" disabled={step === 0} onClick={previous}>← Back</button>{step < steps.length - 1 ? <button type="button" className="button" onClick={next}>Continue to {steps[step + 1]} →</button> : <Link href="/host" className="button">Submit property for review →</Link>}</div>
      </section>
      <aside className="onboarding-plan"><small>Founding host plan</small><strong>$49/month</strong><span>or $490/year</span><hr/><p>Flat platform subscription. Find A Place Booking does not take a percentage of the host’s booking revenue.</p><div className="plan-points"><span>✓ Direct booking page</span><span>✓ Marketplace visibility</span><span>✓ Host dashboard</span><span>✓ Calendar connections</span></div></aside>
    </div>
  );
}
