import { LegalDocument } from "@/components/LegalDocument";
import { copyBlock, loadManagedCopy } from "@/lib/public/managed-copy";
import { getCurrentPolicyVersions } from "@/lib/policies/current";

const defaults = {
  "policy.terms.intro": { eyebrow: "Find A Place", title: "Booking Terms of Service", body: "These terms govern use of Find A Place Booking. By creating or paying for a reservation, the booking guest agrees to these terms and to the property-specific policies presented during checkout." },
  "policy.terms.marketplace": { title: "Marketplace and software role", body: "Find A Place provides listing-hosting, booking software, payment-routing, communication, verification and support tools for independently owned and operated stays. Unless a listing expressly says otherwise, Find A Place does not own, operate, maintain or manage the rental property. The host is responsible for the stay and the guest's reservation is with that host." },
  "policy.terms.communication": { title: "Guest and host communication", body: "Find A Place provides a reservation message thread and may share the contact information needed for the host and guest to communicate about the stay. Guests should use the secure trip page for arrival questions, booking changes and cancellation requests." },
  "policy.terms.verification": { title: "Guest information and verification", body: "The booking guest must provide accurate contact information, including a working email address and phone number. Find A Place may require email and identity verification before payment." },
  "policy.terms.property_rules": { title: "Property rules", body: "The guest must review the property policies saved with the reservation, including house rules, occupancy limits, pet rules, check-in and checkout requirements, cancellation terms and any uploaded policy document." },
  "policy.terms.charges": { title: "Charges, taxes and payment processing", body: "The checkout total may include lodging, host fees, add-ons and applicable taxes calculated for the reservation. The guest payment is processed on the host's connected merchant account. Find A Place receives a host-paid platform commission through the processor's application-fee mechanism. Tax amounts charged to the guest remain in the host's connected account payment proceeds and are not retained by Find A Place. The host's payment processor separately charges its processing fees to the host account." },
  "policy.terms.cancellations": { title: "Cancellations and refunds", body: "Cancellation and refund requests are decided by the host under the property policy accepted for the reservation, subject to applicable law. Sending a cancellation request does not itself create a refund. If a host approves a guest refund, the refund is funded from the host-owned connected-account charge. Find A Place's platform commission is earned when the paid booking connects the guest and host and is not refunded or reversed as part of a guest cancellation or refund. The host remains responsible for the amount of any refund it authorizes." },
  "policy.terms.changes": { title: "Reservation changes", body: "A guest may request changes to dates, occupancy or other booking details. A request does not change the reservation until the host approves and applies it. An approved change does not by itself authorize a new charge or refund. If the host separately approves a refund because of a change, Find A Place's original platform commission remains non-refundable." },
  "policy.terms.damage": { title: "Damage and guest responsibility", body: "Guests are responsible for damage, missing property, excessive cleaning, unauthorized guests or pets, rule violations and other costs caused by the guest or the guest's party, subject to evidence and applicable law. Find A Place is not an insurer or property-damage guarantee program." },
  "policy.terms.limitations": { title: "Platform limitations", body: "To the maximum extent permitted by law, Find A Place is not responsible for the physical condition of independently operated properties, host or guest conduct, a host's cancellation decision, personal property loss, third-party acts, travel interruptions or indirect or consequential losses." },
  "policy.terms.safety": { title: "Fraud, safety and enforcement", body: "Find A Place may pause platform access or transactions, request additional verification, preserve records, restrict listings, cooperate with payment providers and authorities, or take other reasonable action to address suspected fraud, chargebacks, safety concerns or legal obligations." },
};

export default async function TermsPage() {
  const [content, versions] = await Promise.all([loadManagedCopy(defaults), getCurrentPolicyVersions()]);
  const get = (key: keyof typeof defaults) => copyBlock(content, key); const intro = get("policy.terms.intro");
  return <LegalDocument eyebrow={intro.eyebrow || "Find A Place"} title={intro.title} version={versions.guestTerms.version} effectiveAt={versions.guestTerms.effectiveAt}><p>{intro.body}</p>{(["policy.terms.marketplace", "policy.terms.communication", "policy.terms.verification", "policy.terms.property_rules", "policy.terms.charges", "policy.terms.cancellations", "policy.terms.changes", "policy.terms.damage", "policy.terms.limitations", "policy.terms.safety"] as const).map((key) => { const block = get(key); return <section key={key}><h2>{block.title}</h2><p>{block.body}</p></section>; })}</LegalDocument>;
}
