import { LegalDocument } from "@/components/LegalDocument";
import { copyBlock, loadManagedCopy } from "@/lib/public/managed-copy";
import { getCurrentPolicyVersions } from "@/lib/policies/current";

const defaults = {
  "policy.cancellation.intro": { eyebrow: "Booking policy", title: "Cancellation Requests & Refunds", body: "Find A Place provides booking software used by independently operated hosts and their guests. Each reservation is subject to the host's cancellation and refund terms shown and accepted before payment." },
  "policy.cancellation.host_terms": { title: "The host's accepted terms govern guest refunds", body: "Hosts set the guest-facing cancellation and refund terms for their property. Those terms are saved with the reservation at booking. Subject to applicable law, the host decides whether a cancellation request is declined, cancelled without a refund, partially refunded or fully refunded." },
  "policy.cancellation.request": { title: "How a guest requests cancellation", body: "The guest can open the secure My Trip page and send a cancellation request directly to the host. The reservation remains confirmed while the request is pending. A request does not guarantee a cancellation or refund." },
  "policy.cancellation.commission": { title: "Find A Place commission is non-refundable", body: "Find A Place earns its platform commission when a paid reservation connects the guest and host through the marketplace. That commission is not refunded, credited back to the host or reversed because the reservation is later cancelled, refunded, shortened or changed." },
  "policy.cancellation.refunds": { title: "Host-approved guest refunds", body: "If the host approves a guest refund, the refund is created against the host's connected payment charge. The host is responsible for the amount it authorizes. A full guest refund may return the guest's full eligible booking charge, including refundable taxes, while the Find A Place commission remains with Find A Place and is borne by the host. Processor fees are controlled by the payment processor and may not be returned." },
  "policy.cancellation.changes": { title: "Reservation changes", body: "A reservation change does not automatically create a refund. If a host separately approves a refund because dates, occupancy or other booking details changed, the host-approved refund is funded from the host payment charge and the original Find A Place commission remains non-refundable." },
  "policy.cancellation.calendar": { title: "Booking record and calendar", body: "Once a host-approved cancellation is completed, Find A Place records the reservation as cancelled and releases its internal availability block. Refund processing can continue separately without keeping the cancelled dates blocked." },
  "policy.cancellation.role": { title: "Find A Place's role", body: "Find A Place does not independently decide ordinary guest cancellation requests or guarantee that a host will approve a refund. Find A Place may provide technical support, preserve reservation records, correct platform or payment errors, and address fraud or safety issues.\n\nNothing in this policy limits rights or obligations that cannot legally be waived, assigned or transferred." },
};

export default async function CancellationPolicyPage() {
  const [content, versions] = await Promise.all([loadManagedCopy(defaults), getCurrentPolicyVersions()]);
  const get = (key: keyof typeof defaults) => copyBlock(content, key); const intro = get("policy.cancellation.intro");
  return <LegalDocument eyebrow={intro.eyebrow || "Booking policy"} title={intro.title} version={versions.cancellationPolicy.version} effectiveAt={versions.cancellationPolicy.effectiveAt}><p>{intro.body}</p>{(["policy.cancellation.host_terms", "policy.cancellation.request", "policy.cancellation.commission", "policy.cancellation.refunds", "policy.cancellation.changes", "policy.cancellation.calendar", "policy.cancellation.role"] as const).map((key) => { const block = get(key); return <section key={key}><h2>{block.title}</h2>{String(block.body || "").split(/\n\s*\n/).filter(Boolean).map((p, i) => <p key={i}>{p}</p>)}</section>; })}</LegalDocument>;
}
