import Link from "next/link";
import { DashboardShell } from "@/components/DashboardShell";

export default function HostDashboardPage() {
  return <DashboardShell active="Overview" title="Host dashboard">
    <div className="host-alert"><div><span>1</span><p><strong>Start with your first property.</strong> Build the listing, then connect its calendar and payout account.</p></div><Link href="/host/onboarding">Start setup →</Link></div>
    <div className="dash-grid metrics"><div><span>Booked revenue</span><strong>$0</strong><small>No bookings yet</small></div><div><span>Upcoming stays</span><strong>0</strong><small>No reservations yet</small></div><div><span>Occupancy</span><strong>—</strong><small>Available after bookings</small></div><div><span>Listing views</span><strong>0</strong><small>No live listings yet</small></div></div>
    <div className="dash-two"><section className="panel"><div className="panel-head"><div><p className="eyebrow dark">Reservations</p><h2>Upcoming stays</h2></div><Link href="/host/reservations">View reservations</Link></div><div className="panel-empty"><strong>No upcoming reservations.</strong><span>Confirmed Find A Place bookings will appear here.</span></div></section><section className="panel occupancy-panel"><div className="panel-head"><div><p className="eyebrow dark">Availability</p><h2>Calendar</h2></div><Link href="/host/calendar">Open calendar</Link></div><div className="panel-empty"><strong>No property calendar connected.</strong><span>Add a property first, then connect its source-of-truth calendar.</span></div></section></div>
    <div className="dash-two"><section className="panel"><div className="panel-head"><div><p className="eyebrow dark">Account checklist</p><h2>Get ready for bookings</h2></div><span className="status-pill status-muted">Not started</span></div><div className="setup-list"><div><b>1</b><span><strong>Business profile</strong><small>Add the person or business managing the stay</small></span></div><div><b>2</b><span><strong>Property listing</strong><small>Photos, amenities, rates, fees and policies</small></span></div><div><b>3</b><span><strong>Payout account</strong><small>Connect where booking proceeds should settle</small></span></div><div><b>4</b><span><strong>Calendar connection</strong><small>Keep outside bookings from appearing available</small></span></div></div></section><section className="panel performance"><p className="eyebrow dark">Network reach</p><h2>Discovery data</h2><div className="panel-empty"><strong>Performance begins after launch.</strong><span>Search impressions, property views and booking sources will appear here.</span></div></section></div>
  </DashboardShell>;
}
